/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AeronaveController;
import model.Aeronave;
import model.Passageiro;
import model.Passagem;
import model.Bagagem;
import model.CheckIn;
import controller.PassageiroController;
import controller.PassagemController;
import controller.BagagemController;
import controller.CheckInController;
import controller.VooController;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Voo;
import static view.Vooo.formatTimestamp;


/**
 *
 * @author Marden
 */
public class BagagemView extends javax.swing.JFrame {

    /**
     * Creates new form PassageiroView
     */
    public BagagemView() {
        initComponents();
        listar();
        listarCheckIn();
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/icons8-bagagem-50.png"));
        jLabel11.setIcon(icon);
        Excluir.setEnabled(false); 
    }
    
    private void limpar(){
        
        id.setText("0");
        peso.setText("");
        destino.setText("");
        status.setText("");
        CheckInCombo.setSelectedItem(null);
       
        peso.requestFocus();
    }
    
    public void listar(){
        
        BagagemController bagagemController = new BagagemController();
        List<Bagagem> lista = bagagemController.read();
        DefaultTableModel dados = (DefaultTableModel)ConsultarBagagem.getModel();
        dados.setNumRows(0);
        
        for(Bagagem bagagem : lista ){
        dados.addRow(new Object[]{
            bagagem.getIdBagagem(),
            bagagem.getPesoKg(),
            bagagem.getDestinoFinal(),
            bagagem.getStatus()
        });
        }
    }
    
   private void listarCheckIn(){
        CheckInController checkInController = new CheckInController();
        List<CheckIn> listarCheckIn = checkInController.read();
        
        CheckInCombo.removeAllItems();
        
        CheckInCombo.addItem("Selecione...");
       
            for(CheckIn checkIn : listarCheckIn){
                
            CheckInCombo.addItem(checkIn.getIdCheckIn() + " - ");
        }
            
            CheckInCombo.setSelectedIndex(0);

    }
   
    
    public void BuscarPassagem(String id, String assento, String classe, String status, Voo voo, Passageiro passageiro){
        this.id.setText(id);
        this.peso.setText(assento);
        this.destino.setText(classe);
        this.status.setText(status);
        this.CheckInCombo.setSelectedItem(voo.getOrigem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsultarBagagem = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        peso = new javax.swing.JTextPane();
        lId = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        CheckInCombo = new javax.swing.JComboBox<>();
        jLabel4 = new javax.swing.JLabel();
        destino = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        Excluir = new javax.swing.JButton();
        Salvar = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        JPanel.setBackground(new java.awt.Color(204, 204, 204));

        ConsultarBagagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Peso", "Destino", "Status"
            }
        ));
        ConsultarBagagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarBagagemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ConsultarBagagem);

        jPanel3.setBackground(new java.awt.Color(255, 255, 255));

        jLabel10.setFont(new java.awt.Font("Arial Black", 1, 18)); // NOI18N
        jLabel10.setText("CADASTRO DE BAGAGEM");

        jScrollPane1.setViewportView(peso);

        lId.setText("ID: ");

        id.setText("0");

        jLabel2.setText("Peso:");

        jLabel5.setText("CheckIn:");

        jLabel3.setText("Destino:");

        jLabel4.setText("Status:");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(200, 200, 200)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 282, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lId)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2))
                                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                    .addGap(9, 9, 9)
                                    .addComponent(jLabel4)))
                            .addComponent(jLabel3))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(destino)
                            .addComponent(status)
                            .addComponent(jScrollPane1)
                            .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(CheckInCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 248, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(lId))
                .addGap(22, 22, 22)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(CheckInCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(204, 204, 204));

        Excluir.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-lixeira-15.png"))); // NOI18N
        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        Salvar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/icons8-salvar-como-15.png"))); // NOI18N
        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        jLabel11.setText(" ");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel11)
                .addGap(25, 25, 25))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(Excluir, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 102, Short.MAX_VALUE)
                    .addComponent(Salvar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 68, Short.MAX_VALUE)
                .addComponent(Salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Excluir)
                .addGap(59, 59, 59))
        );

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 847, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(167, 167, 167)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(17, 17, 17)
                        .addComponent(jLabel1))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 210, Short.MAX_VALUE)
                .addGap(48, 48, 48))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 891, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(31, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    
    
    private void ConsultarBagagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarBagagemMouseClicked
   
        id.setText(ConsultarBagagem.getValueAt(ConsultarBagagem.getSelectedRow(),0).toString());
        peso.setText(ConsultarBagagem.getValueAt(ConsultarBagagem.getSelectedRow(),1).toString());
        destino.setText(ConsultarBagagem.getValueAt(ConsultarBagagem.getSelectedRow(),2).toString());
        CheckInCombo.setSelectedItem(ConsultarBagagem.getValueAt(ConsultarBagagem.getSelectedRow(),3).toString());
        Excluir.setEnabled(true); 
     // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarBagagemMouseClicked

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
     
         Bagagem bagagem = new Bagagem();
        

        bagagem.setPesoKg(Double.parseDouble(peso.getText()));
        bagagem.setDestinoFinal(destino.getText());
        bagagem.setStatus(status.getText());
        
        CheckIn checkIn  = new CheckIn();
        checkIn = (CheckIn) CheckInCombo.getSelectedItem();
        bagagem.setCheckIn(checkIn);
        

        bagagem.setIdBagagem(Integer.parseInt(id.getText()));
        
        BagagemController bagagemController = new BagagemController();
        bagagemController.delete(bagagem);

        JOptionPane.showMessageDialog(null,"Bagagem excluida com sucesso!");
        
       limpar();
       Excluir.setEnabled(false); 

    }//GEN-LAST:event_ExcluirActionPerformed

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed

        
        try{

            if (peso.getText().trim().isEmpty() ||
                    destino.getText().trim().isEmpty() ||
                    status.getText().trim().isEmpty()) {

                JOptionPane.showMessageDialog(null, "Por favor, preencha todos os campos!");
                return;
            }

            int capacidade = Integer.parseInt(peso.getText().trim());
            if (capacidade <= 0) {
                JOptionPane.showMessageDialog(null, "O peso deve ser um número maior que zero!");
                return;
            }
        
        if(id.getText().equals("0")){
        Bagagem bagagem = new Bagagem();
        
        bagagem.setPesoKg(Double.parseDouble(peso.getText()));
        bagagem.setDestinoFinal(destino.getText());
        bagagem.setStatus(status.getText());
        
        
        //
        
        String selecionado = (String) CheckInCombo.getSelectedItem();
       int idCheckIn = Integer.parseInt(selecionado.split(" - ")[0]);
       
       CheckInController checkInController = new CheckInController();
       CheckIn checkIn = checkInController.findById(idCheckIn);
       
       bagagem.setCheckIn((checkIn));
       
       //
       
       
        BagagemController bagagemController = new BagagemController();
        bagagemController.create(bagagem);
        
        int idBagagemInt = bagagemController.getLastId();
        String idBagagemString = Integer.toString(idBagagemInt);
        id.setText(idBagagemString);
        
        listar();
        limpar();
        Excluir.setEnabled(false); 
                
        JOptionPane.showMessageDialog(null,"Bagagem salvo com sucesso!");
        
        }else{
            
        Bagagem bagagem = new Bagagem();
        
        bagagem.setPesoKg(Double.parseDouble(peso.getText()));
        bagagem.setDestinoFinal(destino.getText());
        bagagem.setStatus(status.getText());
        
        
       //
        
        String selecionado = (String) CheckInCombo.getSelectedItem();
       int idCheckIn = Integer.parseInt(selecionado.split(" - ")[0]);
       
       CheckInController checkInController = new CheckInController();
       CheckIn checkIn = checkInController.findById(idCheckIn);
       
       bagagem.setCheckIn((checkIn));
       
       //
       
       
        BagagemController bagagemController = new BagagemController();
        bagagemController.update(bagagem);
        
        listar();
        limpar();
        Excluir.setEnabled(false); 
        
        JOptionPane.showMessageDialog(null,"Bagagem atualizado com sucesso!");
        
        }
        }catch(NumberFormatException e){
            
            JOptionPane.showMessageDialog(null,"O peso deve ser um número válido.");
        }
        
        
    }//GEN-LAST:event_SalvarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BagagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BagagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BagagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BagagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BagagemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CheckInCombo;
    private javax.swing.JTable ConsultarBagagem;
    private javax.swing.JButton Excluir;
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton Salvar;
    private javax.swing.JTextField destino;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lId;
    private javax.swing.JTextPane peso;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
