/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AeronaveController;
import model.Aeronave;
import model.Passageiro;
import model.Passagem;
import model.Bagagem;
import model.CheckIn;
import controller.PassageiroController;
import controller.PassagemController;
import controller.BagagemController;
import controller.CheckInController;
import controller.VooController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Voo;
import static view.Vooo.formatTimestamp;


/**
 *
 * @author Marden
 */
public class BagagemView extends javax.swing.JFrame {

    /**
     * Creates new form PassageiroView
     */
    public BagagemView() {
        initComponents();
        listar();
        listarCheckIn();
    }
    
    private void limpar(){
        
        id.setText("0");
        peso.setText("");
        destino.setText("");
        status.setText("");
        CheckInCombo.setSelectedItem(null);
       
        peso.requestFocus();
    }
    
    public void listar(){
        
        BagagemController bagagemController = new BagagemController();
        List<Bagagem> lista = bagagemController.read();
        DefaultTableModel dados = (DefaultTableModel)ConsultarBagagem.getModel();
        dados.setNumRows(0);
        
        for(Bagagem bagagem : lista ){
        dados.addRow(new Object[]{
            bagagem.getIdBagagem(),
            bagagem.getPesoKg(),
            bagagem.getDestinoFinal(),
            bagagem.getStatus()
        });
        }
    }
    
   private void listarCheckIn(){
        CheckInController checkInController = new CheckInController();
        List<CheckIn> listarCheckIn = checkInController.read();
        
        CheckInCombo.removeAllItems();
        
        CheckInCombo.addItem("Selecione...");
       
            for(CheckIn checkIn : listarCheckIn){
                
            CheckInCombo.addItem(checkIn.getIdCheckIn() + " - ");
        }
            
            CheckInCombo.setSelectedIndex(0);

    }
   
    
    public void BuscarPassagem(String id, String assento, String classe, String status, Voo voo, Passageiro passageiro){
        this.id.setText(id);
        this.peso.setText(assento);
        this.destino.setText(classe);
        this.status.setText(status);
        this.CheckInCombo.setSelectedItem(voo.getOrigem());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        lId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        destino = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        bSalvar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        peso = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        CheckInCombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsultarBagagem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lId.setText("ID: ");

        jLabel2.setText("Peso:");

        jLabel3.setText("Destino:");

        jLabel4.setText("Status:");

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(peso);

        id.setText("0");

        jLabel5.setText("CheckIn:");

        ConsultarBagagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Peso", "Destino", "Status"
            }
        ));
        ConsultarBagagem.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarBagagemMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(ConsultarBagagem);

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addGap(79, 79, 79)
                                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lId)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel2)))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                                .addGap(45, 45, 45)
                                .addComponent(jLabel4)))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(jLabel3)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(destino)
                    .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                    .addComponent(jScrollPane1)
                    .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CheckInCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(672, 672, 672))
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(JPanelLayout.createSequentialGroup()
                            .addGap(121, 121, 121)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(JPanelLayout.createSequentialGroup()
                            .addGap(449, 449, 449)
                            .addComponent(bSalvar)
                            .addGap(18, 18, 18)
                            .addComponent(bExcluir))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(lId))
                .addGap(22, 22, 22)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(destino, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(CheckInCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(39, 39, 39)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar)
                    .addComponent(bExcluir))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    //this.pesoKg = pesoKg;
       // this.destinoFinal = destinoFinal;
       // this.status = status;
       // this.checkIn = checkIn;
    
    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed

         Bagagem bagagem = new Bagagem();
        

        bagagem.setPesoKg(Double.parseDouble(peso.getText()));
        bagagem.setDestinoFinal(destino.getText());
        bagagem.setStatus(status.getText());
        
        CheckIn checkIn  = new CheckIn();
        checkIn = (CheckIn) CheckInCombo.getSelectedItem();
        bagagem.setCheckIn(checkIn);
        

        bagagem.setIdBagagem(Integer.parseInt(id.getText()));
        
        BagagemController bagagemController = new BagagemController();
        bagagemController.delete(bagagem);

        JOptionPane.showMessageDialog(null,"Bagagem excluida com sucesso!");
        
       limpar();

        // TODO add your handling code here:
    }//GEN-LAST:event_bExcluirActionPerformed

    
    
    
    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed

        
        if(id.getText().equals("0")){
        Bagagem bagagem = new Bagagem();
        
        bagagem.setPesoKg(Double.parseDouble(peso.getText()));
        bagagem.setDestinoFinal(destino.getText());
        bagagem.setStatus(status.getText());
        
        
        //
        
        String selecionado = (String) CheckInCombo.getSelectedItem();
       int idCheckIn = Integer.parseInt(selecionado.split(" - ")[0]);
       
       CheckInController checkInController = new CheckInController();
       CheckIn checkIn = checkInController.findById(idCheckIn);
       
       bagagem.setCheckIn((checkIn));
       
       //
       
       
        BagagemController bagagemController = new BagagemController();
        bagagemController.create(bagagem);
        
        int idBagagemInt = bagagemController.getLastId();
        String idBagagemString = Integer.toString(idBagagemInt);
        id.setText(idBagagemString);
        
        listar();
                
        JOptionPane.showMessageDialog(null,"Bagagem salvo com sucesso!");
        
        }else{
            
        Bagagem bagagem = new Bagagem();
        
        bagagem.setPesoKg(Double.parseDouble(peso.getText()));
        bagagem.setDestinoFinal(destino.getText());
        bagagem.setStatus(status.getText());
        
        
       //
        
        String selecionado = (String) CheckInCombo.getSelectedItem();
       int idCheckIn = Integer.parseInt(selecionado.split(" - ")[0]);
       
       CheckInController checkInController = new CheckInController();
       CheckIn checkIn = checkInController.findById(idCheckIn);
       
       bagagem.setCheckIn((checkIn));
       
       //
       
       
        BagagemController bagagemController = new BagagemController();
        bagagemController.update(bagagem);
        
        listar();
        
        JOptionPane.showMessageDialog(null,"Bagagem atualizado com sucesso!");
        
        }
        
    }//GEN-LAST:event_bSalvarActionPerformed

    
    private void ConsultarBagagemMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarBagagemMouseClicked
   
        id.setText(ConsultarBagagem.getValueAt(ConsultarBagagem.getSelectedRow(),0).toString());
        peso.setText(ConsultarBagagem.getValueAt(ConsultarBagagem.getSelectedRow(),1).toString());
        destino.setText(ConsultarBagagem.getValueAt(ConsultarBagagem.getSelectedRow(),2).toString());
        CheckInCombo.setSelectedItem(ConsultarBagagem.getValueAt(ConsultarBagagem.getSelectedRow(),3).toString());
     // TODO add your handling code here:
    }//GEN-LAST:event_ConsultarBagagemMouseClicked

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(BagagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(BagagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(BagagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(BagagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new BagagemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> CheckInCombo;
    private javax.swing.JTable ConsultarBagagem;
    private javax.swing.JPanel JPanel;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bSalvar;
    private javax.swing.JTextField destino;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lId;
    private javax.swing.JTextPane peso;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
