package view;


import controller.PassageiroController;
import java.util.List;
import javax.swing.table.DefaultTableModel;
import model.Passageiro;
import view.PassageiroView;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marden
 */
public class LocalizaPassageiro extends javax.swing.JFrame {
    
    public void listar(){
        
        PassageiroController passageiroController = new PassageiroController();
        List<Passageiro> lista = passageiroController.read();
        DefaultTableModel dados = (DefaultTableModel)TbPassageiro.getModel();
        dados.setNumRows(0);
        
        for(Passageiro passageiro : lista ){
        dados.addRow(new Object[]{
            passageiro.getIdPassageiro(),
            passageiro.getNome(),
            passageiro.getCpfOuPassaport(),
            passageiro.getContato() 
        });
        }
    }
    
    private PassageiroView passageiroView;

    public LocalizaPassageiro(PassageiroView passageiroView) {
        initComponents();
        listar();
        this.passageiroView = passageiroView;
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        TbPassageiro = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        TbPassageiro.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "ID", "Nome", "CPF / Passaport", "Contato"
            }
        ));
        TbPassageiro.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                TbPassageiroMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(TbPassageiro);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 642, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 378, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void TbPassageiroMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_TbPassageiroMouseClicked
        String id = TbPassageiro.getValueAt(TbPassageiro.getSelectedRow(),0).toString();
        String nome = TbPassageiro.getValueAt(TbPassageiro.getSelectedRow(),1).toString();
        String cpf = TbPassageiro.getValueAt(TbPassageiro.getSelectedRow(),2).toString();
        String contato = TbPassageiro.getValueAt(TbPassageiro.getSelectedRow(),3).toString();
        
        passageiroView.BuscarPassageiro(id, nome, cpf, contato);
        this.dispose();

        // TODO add your handling code here:
    }//GEN-LAST:event_TbPassageiroMouseClicked

    /**
     * @param args the command line arguments
     */

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable TbPassageiro;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
