package view;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Marden
 */

import controller.VooController;
import java.util.List;
import javax.swing.ImageIcon;
import javax.swing.table.DefaultTableModel;
import model.Voo;
import static view.Vooo.formatTimestamp;

public class menu extends javax.swing.JFrame {

    /**
     * Creates new form menu
     */
    
    public menu() {
        initComponents();
        
        ImageIcon icon = new ImageIcon(getClass().getResource("/imagens/icons8-avião-50.png"));
        setIconImage(icon.getImage());
        
        listarVoos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        ConsultarVoo = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jMenuBar2 = new javax.swing.JMenuBar();
        jMenu = new javax.swing.JMenu();
        jMenuItem1 = new javax.swing.JMenuItem();
        jMenuItem2 = new javax.swing.JMenuItem();
        jMenuItem3 = new javax.swing.JMenuItem();
        jMenuItem4 = new javax.swing.JMenuItem();
        jMenuItem5 = new javax.swing.JMenuItem();
        jMenuItem6 = new javax.swing.JMenuItem();
        jMenuSair = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Sistema do Aeroporto");
        setResizable(false);
        setSize(new java.awt.Dimension(480, 680));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jScrollPane2.setBackground(new java.awt.Color(0, 0, 0, 1));
        jScrollPane2.setBorder(null);
        jScrollPane2.setForeground(new java.awt.Color(255, 255, 255));
        jScrollPane2.setName(""); // NOI18N
        jScrollPane2.setOpaque(false);
        jScrollPane2.getViewport().setOpaque(false);

        ConsultarVoo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Origem", "Destino", "Status"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(ConsultarVoo);

        getContentPane().add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 60, 400, 300));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Imagens/aviao-ttt.png"))); // NOI18N
        jLabel1.setText(" ");
        jLabel1.setPreferredSize(new java.awt.Dimension(620, 480));
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 620, 410));

        jLabel2.setBackground(new java.awt.Color(0, 0, 0));
        jLabel2.setFont(new java.awt.Font("Arial Black", 0, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Sistema do Aeroporto");
        jLabel2.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 26, 290, 30));

        jMenu.setText("Menu");
        jMenu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Menu(evt);
            }
        });

        jMenuItem1.setText("Aeronave");
        jMenuItem1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirectToAeronave(evt);
            }
        });
        jMenu.add(jMenuItem1);

        jMenuItem2.setText("Bagagem");
        jMenuItem2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirectToBagagem(evt);
            }
        });
        jMenu.add(jMenuItem2);

        jMenuItem3.setText("Check-In");
        jMenuItem3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirectToCheckIn(evt);
            }
        });
        jMenu.add(jMenuItem3);

        jMenuItem4.setText("Passageiro");
        jMenuItem4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirectToPassageiro(evt);
            }
        });
        jMenu.add(jMenuItem4);

        jMenuItem5.setText("Passagem");
        jMenuItem5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirectToPassagem(evt);
            }
        });
        jMenu.add(jMenuItem5);

        jMenuItem6.setText("Voo");
        jMenuItem6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                redirectToVoo(evt);
            }
        });
        jMenu.add(jMenuItem6);

        jMenuBar2.add(jMenu);

        jMenuSair.setText("Sair");
        jMenuSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Sair(evt);
            }
        });
        jMenuBar2.add(jMenuSair);

        setJMenuBar(jMenuBar2);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void redirectToAeronave(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirectToAeronave
        Aeronavee aeronave = new Aeronavee(); // instanciar a nova tela
        aeronave.setDefaultCloseOperation(Aeronavee.DISPOSE_ON_CLOSE);
        aeronave.setVisible(true);
        // this.dispose();
    }//GEN-LAST:event_redirectToAeronave

    private void redirectToBagagem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirectToBagagem
        BagagemView bagagem = new BagagemView(); // instanciar a nova tela
        bagagem.setDefaultCloseOperation(BagagemView.DISPOSE_ON_CLOSE);
        bagagem.setVisible(true);
    }//GEN-LAST:event_redirectToBagagem

    private void Menu(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Menu
        
    }//GEN-LAST:event_Menu

    private void redirectToCheckIn(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirectToCheckIn
        CheckInn checkin = new CheckInn(); // instanciar a nova tela
        checkin.setDefaultCloseOperation(CheckInn.DISPOSE_ON_CLOSE);
        checkin.setVisible(true);
    }//GEN-LAST:event_redirectToCheckIn

    private void redirectToPassageiro(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirectToPassageiro
        PassageiroView passageiro = new PassageiroView(); // instanciar a nova tela
        passageiro.setDefaultCloseOperation(PassageiroView.DISPOSE_ON_CLOSE);
        passageiro.setVisible(true);
    }//GEN-LAST:event_redirectToPassageiro

    private void redirectToPassagem(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirectToPassagem
        PassagemView passagem = new PassagemView(); // instanciar a nova tela
        passagem.setDefaultCloseOperation(PassagemView.DISPOSE_ON_CLOSE);
        passagem.setVisible(true);
    }//GEN-LAST:event_redirectToPassagem

    private void redirectToVoo(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_redirectToVoo
        Vooo voo = new Vooo(); // instanciar a nova tela
        voo.setDefaultCloseOperation(Vooo.DISPOSE_ON_CLOSE);
        voo.setVisible(true);
    }//GEN-LAST:event_redirectToVoo

    public void listarVoos(){
        
        VooController vooController = new VooController();
        List<Voo> lista = vooController.read();
        DefaultTableModel dados = (DefaultTableModel) ConsultarVoo.getModel();
        dados.setNumRows(0);
        
        for(Voo voo : lista){
        
            dados.addRow(new Object[]{
                voo.getOrigem(),
                voo.getDestino(),
                voo.getStatus(),
        });
    }
}
    
    private void Sair(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Sair
        this.dispose();
    }//GEN-LAST:event_Sair

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ConsultarVoo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenu jMenu;
    private javax.swing.JMenuBar jMenuBar2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JMenuItem jMenuItem2;
    private javax.swing.JMenuItem jMenuItem3;
    private javax.swing.JMenuItem jMenuItem4;
    private javax.swing.JMenuItem jMenuItem5;
    private javax.swing.JMenuItem jMenuItem6;
    private javax.swing.JMenu jMenuSair;
    private javax.swing.JScrollPane jScrollPane2;
    // End of variables declaration//GEN-END:variables
}
