/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AeronaveController;
import model.Aeronave;
import model.Passageiro;
import model.Passagem;
import controller.PassageiroController;
import controller.PassagemController;
import controller.VooController;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Voo;
import static view.Vooo.formatTimestamp;


/**
 *
 * @author Marden
 */
public class PassagemView extends javax.swing.JFrame {

    /**
     * Creates new form PassageiroView
     */
    public PassagemView() {
        initComponents();
        listar();
        listarPassageiro();
        listarVoo();
    }
    
    private void limpar(){
        
        id.setText("0");
        assento.setText("");
        classe.setText("");
        status.setText("");
        VooCombo.setSelectedItem(null);
        PassageiroCombo.setSelectedItem(null);
       
        assento.requestFocus();
    }
    
    public void listar(){
        
        PassagemController passagemController = new PassagemController();
        List<Passagem> lista = passagemController.read();
        DefaultTableModel dados = (DefaultTableModel)ConsultarPassagem.getModel();
        dados.setNumRows(0);
        
        for(Passagem passagem : lista ){
        dados.addRow(new Object[]{
            passagem.getIdPassagem(),
            passagem.getClasse(),
            passagem.getStatusPgto()
        });
        }
    }
    
   private void listarPassageiro(){
        PassageiroController passageiroController = new PassageiroController();
        List<Passageiro> listarPassageiro = passageiroController.read();
        
        PassageiroCombo.removeAllItems();
        
        PassageiroCombo.addItem("Selecione...");
       
            for(Passageiro passageiro : listarPassageiro){
                
            PassageiroCombo.addItem(passageiro.getIdPassageiro() + " - " + passageiro.getNome());
        }
            
            PassageiroCombo.setSelectedIndex(0);

    }
   
      private void listarVoo(){
        VooController vooController = new VooController();
        List<Voo> listarVoo = vooController.read();
        
        VooCombo.removeAllItems();
        
        VooCombo.addItem("Selecione...");
       
            for(Voo voo : listarVoo){
                
            VooCombo.addItem(voo.getIdVoo() + " - " + voo.getOrigem());
        }
            
            VooCombo.setSelectedIndex(0);

    }
    
    public void BuscarPassagem(String id, String assento, String classe, String status, Voo voo, Passageiro passageiro){
        this.id.setText(id);
        this.assento.setText(assento);
        this.classe.setText(classe);
        this.status.setText(status);
        this.VooCombo.setSelectedItem(voo.getOrigem());
        this.PassageiroCombo.setSelectedItem(passageiro.getNome());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        JPanel = new javax.swing.JPanel();
        lId = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        classe = new javax.swing.JTextField();
        status = new javax.swing.JTextField();
        bSalvar = new javax.swing.JButton();
        bExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        assento = new javax.swing.JTextPane();
        jLabel1 = new javax.swing.JLabel();
        id = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        VooCombo = new javax.swing.JComboBox<>();
        PassageiroCombo = new javax.swing.JComboBox<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        ConsultarPassagem = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lId.setText("ID: ");

        jLabel2.setText("Assento:");

        jLabel3.setText("Classe:");

        jLabel4.setText("Status Pag.:");

        bSalvar.setText("Salvar");
        bSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bSalvarActionPerformed(evt);
            }
        });

        bExcluir.setText("Excluir");
        bExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bExcluirActionPerformed(evt);
            }
        });

        jScrollPane1.setViewportView(assento);

        id.setText("0");

        jLabel5.setText("Voo:");

        jLabel6.setText("Passageiro:");

        ConsultarPassagem.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Id", "Assento", "Classe", "StatusPag"
            }
        ));
        jScrollPane2.setViewportView(ConsultarPassagem);

        javax.swing.GroupLayout JPanelLayout = new javax.swing.GroupLayout(JPanel);
        JPanel.setLayout(JPanelLayout);
        JPanelLayout.setHorizontalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(121, 121, 121)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(72, 72, 72)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 539, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(JPanelLayout.createSequentialGroup()
                                .addGap(377, 377, 377)
                                .addComponent(bSalvar)
                                .addGap(18, 18, 18)
                                .addComponent(bExcluir)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, JPanelLayout.createSequentialGroup()
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(45, 45, 45)
                        .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lId)
                            .addComponent(jLabel5)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(JPanelLayout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel6)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(PassageiroCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(classe)
                        .addComponent(status, javax.swing.GroupLayout.DEFAULT_SIZE, 248, Short.MAX_VALUE)
                        .addComponent(jScrollPane1)
                        .addComponent(id, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(VooCombo, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addGap(672, 672, 672))
        );
        JPanelLayout.setVerticalGroup(
            JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(JPanelLayout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(id)
                    .addComponent(lId))
                .addGap(22, 22, 22)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(classe, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(status, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(VooCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(PassageiroCombo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(JPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bSalvar)
                    .addComponent(bExcluir))
                .addGap(40, 40, 40))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(JPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 671, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(JPanel, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(14, 14, 14))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bExcluirActionPerformed

         Passagem passagem = new Passagem();

        passagem.setAssento(assento.getText());
        passagem.setClasse(classe.getText());
        passagem.setStatusPgto(status.getText());
        Voo voo  = new Voo();
        voo = (Voo) VooCombo.getSelectedItem();
        passagem.setVoo(voo);
        Passageiro passageiro  = new Passageiro();
        passageiro = (Passageiro) PassageiroCombo.getSelectedItem();
        passagem.setPassageiro(passageiro);
        

        passagem.setIdPassagem(Integer.parseInt(id.getText()));
        
        PassagemController passagemController = new PassagemController();
        passagemController.delete(passagem);

        JOptionPane.showMessageDialog(null,"Passagem excluida com sucesso!");
        
       limpar();

        // TODO add your handling code here:
    }//GEN-LAST:event_bExcluirActionPerformed

    private void bSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bSalvarActionPerformed

        
        if(id.getText().equals("0")){
        Passagem passagem = new Passagem();

        passagem.setAssento(assento.getText());
        passagem.setClasse(classe.getText());
        passagem.setStatusPgto(status.getText());
        
        
        //
        
        String selecionado = (String) PassageiroCombo.getSelectedItem();
       int idPassageiro = Integer.parseInt(selecionado.split(" - ")[0]);
       
       PassageiroController passageiroController = new PassageiroController();
       Passageiro passageiro = passageiroController.findById(idPassageiro);
       
       passagem.setPassageiro((passageiro));
       
       //
       
       String selecionadoVoo = (String) VooCombo.getSelectedItem();
       int idVoo = Integer.parseInt(selecionadoVoo.split(" - ")[0]);
       
       VooController vooController = new VooController();
       Voo voo = vooController.findById(idVoo);
       
       passagem.setVoo((voo));
       
       //
       


        PassagemController passagemController = new PassagemController();
        passagemController.create(passagem);
        
        int idPassagemInt = passagemController.getLastId();
        String idPassagemString = Integer.toString(idPassagemInt);
        id.setText(idPassagemString);
        
        listar();
                
        JOptionPane.showMessageDialog(null,"Passagem salvo com sucesso!");
        
        }else{
            
        Passagem passagem = new Passagem();

        passagem.setAssento(assento.getText());
        passagem.setClasse(classe.getText());
        passagem.setStatusPgto(status.getText());
        Voo voo  = new Voo();
        voo = (Voo) VooCombo.getSelectedItem();
        passagem.setVoo(voo);
        Passageiro passageiro  = new Passageiro();
        passageiro = (Passageiro) PassageiroCombo.getSelectedItem();
        passagem.setPassageiro(passageiro);

        PassagemController passagemController = new PassagemController();
        passagemController.update(passagem);
        
        listar();
        
        JOptionPane.showMessageDialog(null,"Passagem atualizado com sucesso!");
        
        }
        
        
    }//GEN-LAST:event_bSalvarActionPerformed

    
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(PassagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(PassagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(PassagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(PassagemView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PassagemView().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable ConsultarPassagem;
    private javax.swing.JPanel JPanel;
    private javax.swing.JComboBox<String> PassageiroCombo;
    private javax.swing.JComboBox<String> VooCombo;
    private javax.swing.JTextPane assento;
    private javax.swing.JButton bExcluir;
    private javax.swing.JButton bSalvar;
    private javax.swing.JTextField classe;
    private javax.swing.JLabel id;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel lId;
    private javax.swing.JTextField status;
    // End of variables declaration//GEN-END:variables
}
