/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import controller.AeronaveController;
import controller.VooController;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import model.Aeronave;
import model.Voo;

/**
 *
 * @author Carlos
 */
public class Vooo extends javax.swing.JFrame {

    /**
     * Creates new form Vooo
     */
    public Vooo() {
        initComponents();
        listarAeronaves();
        listarVoos();
        Excluir.setEnabled(false);
    }
    
    private void limparDados(){
        Origem.setText("");
        Destino.setText("");
        DataHoraPartida.setText("");
        DataHoraChegada.setText("");
        Status.setText("");
   
        }
    
    public static String formatTimestamp(Timestamp timestamp) {
    if (timestamp == null) return "";
    SimpleDateFormat sdf = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
    return sdf.format(new Date(timestamp.getTime()));
}
    
    public void listarVoos(){
        
        VooController vooController = new VooController();
        List<Voo> lista = vooController.read();
        DefaultTableModel dados = (DefaultTableModel) ConsultarVoo.getModel();
        dados.setNumRows(0);
        
        for(Voo voo : lista){
            String partidaFormatada = formatTimestamp(voo.getDataHoraPartida());
            String chegadaFormatada = formatTimestamp(voo.getDataHoraChegada());
        
            dados.addRow(new Object[]{
                voo.getIdVoo(),
                voo.getOrigem(),
                voo.getDestino(),
                partidaFormatada,
                chegadaFormatada,
                voo.getStatus(),
                voo.getAeronave().getIdAeronave()
        });
    }
}

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane5 = new javax.swing.JScrollPane();
        Origem = new javax.swing.JTextPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Destino = new javax.swing.JTextPane();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        DataHoraChegada = new javax.swing.JTextPane();
        Salvar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        Id = new javax.swing.JTextPane();
        Editar1 = new javax.swing.JButton();
        Excluir = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane7 = new javax.swing.JScrollPane();
        DataHoraPartida = new javax.swing.JTextPane();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane8 = new javax.swing.JScrollPane();
        Status = new javax.swing.JTextPane();
        jLabel8 = new javax.swing.JLabel();
        AeronaveCombo = new javax.swing.JComboBox<>();
        jPanel5 = new javax.swing.JPanel();
        jScrollPane6 = new javax.swing.JScrollPane();
        ConsultarVoo = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jLabel3.setText("Origem:");

        jScrollPane5.setViewportView(Origem);

        jScrollPane1.setViewportView(Destino);

        jLabel4.setText("Destino:");

        jLabel5.setText("DataHoraPartida:");

        jScrollPane4.setViewportView(DataHoraChegada);

        Salvar.setText("Salvar");
        Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SalvarActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(Id);

        Editar1.setText("Editar");
        Editar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Editar1ActionPerformed(evt);
            }
        });

        Excluir.setText("Excluir");
        Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExcluirActionPerformed(evt);
            }
        });

        jLabel6.setText("DataHoraChegada");

        jScrollPane7.setViewportView(DataHoraPartida);

        jLabel7.setText("Status");

        jScrollPane8.setViewportView(Status);

        jLabel8.setText("Aeronave:");

        AeronaveCombo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AeronaveComboActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(50, 50, 50)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(Salvar)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Editar1)
                                .addGap(18, 18, 18)
                                .addComponent(Excluir))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 183, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel6)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane4))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel5)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(AeronaveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(0, 669, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5)
                    .addComponent(jScrollPane7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel6)
                    .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel7)
                    .addComponent(jScrollPane8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(AeronaveCombo, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 9, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Salvar)
                    .addComponent(Editar1)
                    .addComponent(Excluir))
                .addGap(14, 14, 14))
        );

        jTabbedPane1.addTab("Dados Voo", jPanel1);

        ConsultarVoo.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "IDVoo", "Origem", "Destino", "DataHoraPartida", "DataHoraChegada", "Status", "IDAeronave"
            }
        ));
        ConsultarVoo.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ConsultarVooMouseClicked(evt);
            }
        });
        jScrollPane6.setViewportView(ConsultarVoo);

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.DEFAULT_SIZE, 909, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane6, javax.swing.GroupLayout.PREFERRED_SIZE, 238, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(27, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Consultar Voos", jPanel5);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1001, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 921, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(74, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 318, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jTabbedPane1)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SalvarActionPerformed
       Voo voo = new Voo();
       try{
           String texto = DataHoraPartida.getText();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date data = formato.parse(texto);
            Timestamp timeStamp = new Timestamp(data.getTime());
            voo.setDataHoraPartida(timeStamp);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Data e hora invalidas, use dd/MM/yyyy HH:mm:ss");  
        }
        try{
           String texto = DataHoraChegada.getText();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date data = formato.parse(texto);
            Timestamp timeStamp = new Timestamp(data.getTime());
            voo.setDataHoraChegada(timeStamp);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Data e hora invalidas, use dd/MM/yyyy HH:mm:ss");  
        }
       
       voo.setOrigem(Origem.getText());
       voo.setDestino(Destino.getText());
       voo.setStatus(Status.getText());
       
       String selecionado = (String) AeronaveCombo.getSelectedItem();
       int idAeronave = Integer.parseInt(selecionado.split(" - ")[0]);
       
       AeronaveController aeronaveController = new AeronaveController();
       Aeronave aeronave = aeronaveController.findById(idAeronave);
       
       voo.setAeronave((aeronave));
       
       VooController vooController = new VooController();
       
       vooController.create(voo);
       limparDados();
       listarVoos();
      
    }//GEN-LAST:event_SalvarActionPerformed

    
    private void listarAeronaves(){
        AeronaveController aeronaveController = new AeronaveController();
        List<Aeronave> listarAeronave = aeronaveController.read();
        
        AeronaveCombo.removeAllItems();
        
        AeronaveCombo.addItem("Selecione...");
       
            for(Aeronave aeronave : listarAeronave){
                
            AeronaveCombo.addItem(aeronave.getIdAeronave() + " - " + aeronave.getModelo());
        }
            
            AeronaveCombo.setSelectedIndex(0);

    }
    
    
    private void Editar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Editar1ActionPerformed
       Voo voo = new Voo();
       
       
       try{
           String texto = DataHoraPartida.getText();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date data = formato.parse(texto);
            Timestamp timeStamp = new Timestamp(data.getTime());
            voo.setDataHoraPartida(timeStamp);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Data e hora invalidas, use dd/MM/yyyy HH:mm:ss");  
        }try{
           String texto = DataHoraChegada.getText();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date data = formato.parse(texto);
            Timestamp timeStamp = new Timestamp(data.getTime());
            voo.setDataHoraChegada(timeStamp);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Data e hora invalidas, use dd/MM/yyyy HH:mm:ss");  
        }
       
       voo.setIdVoo(Integer.parseInt(Id.getText()));
       voo.setOrigem(Origem.getText());
       voo.setDestino(Destino.getText());
       voo.setStatus(Status.getText());
       
       String selecionado = (String) AeronaveCombo.getSelectedItem();
       int idAeronave = Integer.parseInt(selecionado.split(" - ")[0]);
       
       AeronaveController aeronaveController = new AeronaveController();
       Aeronave aeronave = aeronaveController.findById(idAeronave);
       
       voo.setAeronave((aeronave));
       
       VooController vooController = new VooController();
       
       vooController.update(voo);
       listarVoos();
       limparDados();
       
       
       
    }//GEN-LAST:event_Editar1ActionPerformed

    private void ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExcluirActionPerformed
        Voo voo = new Voo();
        try{
           String texto = DataHoraPartida.getText();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date data = formato.parse(texto);
            Timestamp timeStamp = new Timestamp(data.getTime());
            voo.setDataHoraPartida(timeStamp);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Data e hora invalidas, use dd/MM/yyyy HH:mm:ss");  
        }try{
           String texto = DataHoraChegada.getText();
       SimpleDateFormat formato = new SimpleDateFormat("dd/MM/yyyy HH:mm:ss");
            Date data = formato.parse(texto);
            Timestamp timeStamp = new Timestamp(data.getTime());
            voo.setDataHoraChegada(timeStamp);
        } catch (ParseException ex) {
            JOptionPane.showMessageDialog(null,"Data e hora invalidas, use dd/MM/yyyy HH:mm:ss");  
        }
       
        voo.setIdVoo(Integer.parseInt(Id.getText())); 
     
        voo.setOrigem(Origem.getText());
        voo.setDestino(Destino.getText());
        voo.setStatus(Status.getText());

        String selecionado = (String) AeronaveCombo.getSelectedItem();
       int idAeronave = Integer.parseInt(selecionado.split(" - ")[0]);
       
       AeronaveController aeronaveController = new AeronaveController();
       Aeronave aeronave = aeronaveController.findById(idAeronave);
       
       voo.setAeronave((aeronave));
       
       VooController vooController = new VooController();
       vooController.delete(voo);
       
       listarVoos();
       limparDados();
       
       Excluir.setEnabled(false);
      
        
    }//GEN-LAST:event_ExcluirActionPerformed

    private void ConsultarVooMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ConsultarVooMouseClicked

        jTabbedPane1.setSelectedIndex(0);
        
        Id.setText(ConsultarVoo.getValueAt(ConsultarVoo.getSelectedRow(),0).toString());
        Origem.setText(ConsultarVoo.getValueAt(ConsultarVoo.getSelectedRow(),1).toString());
        Destino.setText(ConsultarVoo.getValueAt(ConsultarVoo.getSelectedRow(),2).toString());
        DataHoraPartida.setText(ConsultarVoo.getValueAt(ConsultarVoo.getSelectedRow(),3).toString());
        DataHoraChegada.setText(ConsultarVoo.getValueAt(ConsultarVoo.getSelectedRow(),4).toString());
        Status.setText(ConsultarVoo.getValueAt(ConsultarVoo.getSelectedRow(),5).toString());
        AeronaveCombo.setSelectedItem(ConsultarVoo.getValueAt(ConsultarVoo.getSelectedRow(),6).toString());
        Excluir.setEnabled(true);

    }//GEN-LAST:event_ConsultarVooMouseClicked

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked

    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void AeronaveComboActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AeronaveComboActionPerformed

    }//GEN-LAST:event_AeronaveComboActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Vooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Vooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Vooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Vooo.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Vooo().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox<String> AeronaveCombo;
    private javax.swing.JTable ConsultarVoo;
    private javax.swing.JTextPane DataHoraChegada;
    private javax.swing.JTextPane DataHoraPartida;
    private javax.swing.JTextPane Destino;
    private javax.swing.JButton Editar1;
    private javax.swing.JButton Excluir;
    private javax.swing.JTextPane Id;
    private javax.swing.JTextPane Origem;
    private javax.swing.JButton Salvar;
    private javax.swing.JTextPane Status;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JScrollPane jScrollPane6;
    private javax.swing.JScrollPane jScrollPane7;
    private javax.swing.JScrollPane jScrollPane8;
    private javax.swing.JTabbedPane jTabbedPane1;
    // End of variables declaration//GEN-END:variables

  
}
